files:
  include: 'src/**/*.scss'
rules:
  indentation: 2
  property-sort-order: 0
  hex-notation: 0
  empty-line-between-blocks: 0
  class-name-format:
    - 2
    - convention: hyphenatedbem
  space-after-comma: 0
  variable-name-format:
    - 2
    - convention: camelcase
  nesting-depth:
    - 1
    - max-depth: 5  
